- name: Check required fitness variables
  assert:
    that:
      - user_name is defined
    msg: Required variable missing.

- name: Fitness Test
  become: yes
  become_user: "{{ user_name }}"
  command: zen-cli zcbenchmark createjoinsplit 1
  register: benchmark
- debug:
    msg: "Benchmark time: {{ (benchmark.stdout | from_json)[0].runningtime }}"
- name: Fitness Result
  assert:
    that:
      - "(benchmark.stdout | from_json)[0].runningtime < 300"
    msg: "Challenges must complete in under 300s"