---
- import_tasks: tracker-config.yml
  notify:
    - restart nodetracker

- import_tasks: tracker-container.yml
  notify:
    - restart nodetracker

- import_tasks: tracker-service.yml
  notify:
    - restart nodetracker
