---
- name: Install Tracker Container
  docker_container:
    name: "{{ nodetracker_docker_ctr_name }}"
    image: "aschultz5/zen-nodetracker:{{ nodetracker_ver }}"
    state: present
    restart_policy: unless-stopped
    user: "{{ zend_user_id }}"
    log_driver: journald
    env:
      ZENCONF: /mnt/zen/zen.conf
    volumes:
      - "{{ nodetracker_dir }}/config:/home/node/app/config"
      - "{{ zend_dir }}:/mnt/zen:ro"
    networks:
      - name: "{{ zend_docker_net_name }}"

- name: Tracker Service File
  copy:
    dest: "/lib/systemd/system/{{ nodetracker_svc_name }}.service"
    owner: root
    content: |
      [Unit]
      Description=ZenCash nodetracker
      Requires={{ zend_svc_name }}.service
      After={{ zend_svc_name }}.service

      [Service]
      Type=oneshot
      RemainAfterExit=yes
      TimeoutStartSec=100
      ExecStart=/usr/bin/docker start {{ nodetracker_docker_ctr_name }}
      ExecStop=/usr/bin/docker stop {{ nodetracker_docker_ctr_name }}

      [Install]
      WantedBy=multi-user.target
  notify:
    - systemd daemon-reload

- name: Enable Tracker Service
  service:
    name: "{{ nodetracker_svc_name }}.service"
    enabled: yes
