---
# Tracker service
- name: Create tracker service file
  copy:
    dest: "/lib/systemd/system/{{ secnode_tracker_svc_name }}.service"
    owner: root
    content: |
      [Unit]
      Description=ZenCash node daemon installed on {{ secnode_tracker_dir }}
      Requires={{ zennode_zend_svc_name }}.service
      After={{ zennode_zend_svc_name }}.service

      [Service]
      User={{ zennode_user_name }}
      Type=simple
      WorkingDirectory={{ secnode_tracker_dir }}
      ExecStart=/usr/local/bin/node {{ secnode_tracker_dir }}/app.js
      Restart=always
      RestartSec=10

      [Install]
      WantedBy=multi-user.target
  register: secnode_tracker_svc_file

- name: Systemd daemon-reload
  systemd:
    daemon_reload: true
  when: secnode_tracker_svc_file.changed

# Activate tracker
- name: Start and enable tracker service
  service:
    name: "{{ secnode_tracker_svc_name }}.service"
    enabled: yes
    state: started