---
- name: Install Tracker Container
  docker_container:
    name: "{{ snode_tracker_svc_name }}"
    image: "aschultz5/zen-nodetracker:{{ snode_tracker_ver|d('latest') }}"
    state: present
    restart_policy: unless-stopped
    user: "{{ zend_user_id|d(omit,true) }}"
    log_driver: journald
    env:
      ZENCONF: /mnt/zen/zen.conf
    volumes:
      - "{{ snode_tracker_dir }}/config:/home/node/app/config"
      - "{{ zend_dir }}:/mnt/zen:ro"
    networks:
      - name: "{{ zend_docker_net_name }}"

- name: Tracker Service File
  copy:
    dest: "/lib/systemd/system/{{ snode_tracker_svc_name }}.service"
    owner: root
    content: |
      [Unit]
      Description=ZenCash nodetracker
      Requires={{ zend_svc_name }}.service
      After={{ zend_svc_name }}.service

      [Service]
      Type=oneshot
      RemainAfterExit=yes
      ExecStart=/usr/bin/docker start {{ snode_tracker_svc_name }}
      ExecStop=/usr/bin/docker stop {{ snode_tracker_svc_name }}

      [Install]
      WantedBy=multi-user.target
  notify:
    - systemd daemon-reload

- name: Enable Tracker Service
  service:
    name: "{{ snode_tracker_svc_name }}.service"
    enabled: yes
