---
# Tracker service
- name: Create tracker service file
  copy:
    dest: "/lib/systemd/system/{{ secnode_tracker_svc_name }}.service"
    owner: root
    content: |
      [Unit]
      Description=ZenCash nodetracker
      Requires={{ zennode_zend_svc_name }}.service
      After={{ zennode_zend_svc_name }}.service

      [Service]
      Type=oneshot
      RemainAfterExit=yes
      ExecStart=/usr/bin/docker start {{ secnode_tracker_svc_name }}
      ExecStop=/usr/bin/docker stop {{ secnode_tracker_svc_name }}

      [Install]
      WantedBy=multi-user.target
  register: secnode_tracker_svc_file

- name: Systemd daemon-reload
  systemd:
    daemon_reload: true
  when: secnode_tracker_svc_file.changed

# Activate tracker
- name: Start and enable tracker service
  service:
    name: "{{ secnode_tracker_svc_name }}.service"
    enabled: yes
    state: started