- name: Check required tracker variables
  assert:
    that:
      - secnode_alert_email is defined
      - secnode_region is defined
      - secnode_stake_taddr is defined
      - secnode_tracker_dir is defined
      - secnode_tracker_svc_name is defined
      - secnode_user_name is defined
      - secnode_zend_svc_name is defined
    msg: Required variable missing.

- name: Stop tracker service before making changes
  service:
    name: "{{ secnode_tracker_svc_name }}.service"
    state: stopped
  ignore_errors: yes

# expect module dependencies
- name: Install python3-pip
  apt: name=python3-pip
- name: Install python3-virtualenv
  apt: name=python3-virtualenv
- name: Install pexpect
  pip: name=pexpect

# tracker dependencies
- name: Install build-essential
  apt: name=build-essential
- name: Install software-properties-common
  apt: name=software-properties-common
- name: Install apt-transport-https
  apt: name=apt-transport-https
- name: Install git
  apt: name=git
- name: Install npm
  apt: name=npm
- name: Install n
  npm:
    name: n
    global: yes
- name: n latest
  command: n latest

# Install tracker from source
- name: tracker source directory
  file:
    dest: "{{ secnode_tracker_dir }}"
    state: directory
    owner: "{{ secnode_user_name }}"
- name: Secure Node Tracker Install
  block:
    - name: Git tracker source
      become: yes
      become_user: "{{ secnode_user_name }}"
      git:
        repo: https://github.com/ZencashOfficial/secnodetracker.git
        dest: "{{ secnode_tracker_dir }}"
        version: "1f5970620f5d7b9e20e140fa7203b3ce328f979c"
        force: yes
    - name: npm install
      npm:
        path: "{{ secnode_tracker_dir }}"
        state: latest
    - name: node setup
      expect:
        chdir: "{{ secnode_tracker_dir }}"
        command: node setup.js
        responses:
          (?i)transparent: "{{ secnode_stake_taddr }}"
          (?i)email: "{{ secnode_alert_email }}"
          FQDN: "{{ inventory_hostname }}"
          IP: "4"
          (?i)region: "{{ secnode_region }}"
        echo: yes
        timeout: 5
    - name: stakeaddr cleanup
      copy:
        dest: "{{ secnode_tracker_dir }}/config/stakeaddr"
        content: "{{ secnode_stake_taddr }}"
    - name: email cleanup
      copy:
        dest: "{{ secnode_tracker_dir }}/config/email"
        content: "{{ secnode_alert_email }}"
    - name: fqdn cleanup
      copy:
        dest: "{{ secnode_tracker_dir }}/config/fqdn"
        content: "{{ inventory_hostname }}"
    - name: ip cleanup
      copy:
        dest: "{{ secnode_tracker_dir }}/config/ipv"
        content: "4"
    - name: region cleanup
      copy:
        dest: "{{ secnode_tracker_dir }}/config/region"
        content: "{{ secnode_region }}"

  become: yes
  become_user: "{{ secnode_user_name }}"

# Tracker service
- name: Create tracker service file
  copy:
    dest: "/lib/systemd/system/{{ secnode_tracker_svc_name }}.service"
    owner: root
    content: |
      [Unit]
      Description=ZenCash node daemon installed on {{ secnode_tracker_dir }}
      Requires={{ secnode_zend_svc_name }}.service
      After={{ secnode_zend_svc_name }}.service

      [Service]
      User={{ secnode_user_name }}
      Type=simple
      WorkingDirectory={{ secnode_tracker_dir }}
      ExecStart=/usr/local/bin/node {{ secnode_tracker_dir }}/app.js
      Restart=always
      RestartSec=10

      [Install]
      WantedBy=multi-user.target
  register: secnode_tracker_svc_file

- name: Systemd daemon-reload
  systemd:
    daemon_reload: true
  when: secnode_tracker_svc_file.changed

# Activate tracker
- name: Start and enable tracker service
  service:
    name: "{{ secnode_tracker_svc_name }}.service"
    enabled: yes
    state: started
