---
- name: Check required tracker variables
  assert:
    that:
      - secnode_alert_email is defined
      - secnode_region is defined
      - secnode_stake_taddr is defined
      - secnode_category is defined
      - secnode_tracker_dir is defined
      - secnode_tracker_svc_name is defined
      - zennode_user_name is defined
      - zennode_zend_svc_name is defined
    msg: Required variable missing.

- name: tracker source directory
  file:
    dest: "{{ secnode_tracker_dir }}"
    state: directory
    owner: "{{ zennode_user_name }}"
- name: NodeTracker Config
  block:
    - name: Nodetracker config parent directory
      file:
        path: "{{ secnode_tracker_dir }}/config"
        state: directory
        owner: "{{ zennode_user_name }}"
        mode: 0777

    - set_fact:
        tracker_config_path: "{{ secnode_tracker_dir }}/config/config.json"

    - name: Check if tracker config exists
      stat:
        path: "{{ tracker_config_path }}"
      register: stat_result

    - name: Extract Existing NodeTracker Config
      block:
        - name: Read existing tracker config
          slurp:
            src: "{{ tracker_config_path }}"
          register: existing_tracker_config

        - name: Convert tracker config content to dict
          set_fact:
            secnode_tracker_config: "{{ existing_tracker_config['content'] | b64decode | from_json }}"
      when: stat_result.stat.exists

    - name: NodeTracker Config Template
      template:
        src: config.j2
        dest: "{{ tracker_config_path }}"
        owner: "{{ zennode_user_name }}"
        mode: 0664

  become: yes
  become_user: "{{ zennode_user_name }}"
