- name: Check required tracker variables
  assert:
    that:
      - ansible_default_ipv4 is defined
      - secnode_alert_email is defined
      - secnode_region is defined
      - secnode_stake_taddr is defined
      - secnode_tracker_dir is defined
      - secnode_tracker_svc_name is defined
      - secnode_user_name is defined
      - secnode_zend_svc_name is defined
    msg: Required variable missing.

- name: Stop tracker service before making changes
  service:
    name: "{{ secnode_tracker_svc_name }}.service"
    state: stopped
  ignore_errors: yes

# expect module dependencies
- name: Install python3-pip
  apt: name=python3-pip
- name: Install python3-virtualenv
  apt: name=python3-virtualenv
- name: Install pexpect
  pip: name=pexpect

# tracker dependencies
- name: Install build-essential
  apt: name=build-essential
- name: Install software-properties-common
  apt: name=software-properties-common
- name: Install apt-transport-https
  apt: name=apt-transport-https
- name: Install git
  apt: name=git
- name: Install npm
  apt: name=npm
- name: Install n
  npm:
    name: n
    global: yes
- name: npm cache clean
  command: npm cache clean -f
- name: n 10.12.0
  command: n 10.12.0

# Install tracker from source
- name: tracker source directory
  file:
    dest: "{{ secnode_tracker_dir }}"
    state: directory
    owner: "{{ secnode_user_name }}"
- name: Secure Node Tracker Install
  block:
    - name: Git tracker source
      become: yes
      become_user: "{{ secnode_user_name }}"
      git:
        repo: https://github.com/ZencashOfficial/nodetracker.git
        dest: "{{ secnode_tracker_dir }}"
        version: "v0.3.1-beta"
        force: yes
    - name: npm install
      npm:
        path: "{{ secnode_tracker_dir }}"
        state: latest

    # setup.js writes the prompts twice if they have an existing value. It uses
    # escape characters to erase the first write, but the expect module detects them
    - name: delete nodetracker config
      file:
        path: "{{ secnode_tracker_dir }}/config/config.json"
        state: absent
    - name: node setup
      expect:
        chdir: "{{ secnode_tracker_dir }}"
        command: node setup.js
        responses:
          Enter the node type: "secure"
          Staking transparent address: "{{ secnode_stake_taddr }}"
          Alert email address: "{{ secnode_alert_email }}"
          Full hostname: "{{ inventory_hostname }}"
          IP address version used for connection: "4"
          Region: "{{ secnode_region }}"
          A category may be used to uniquely identify a set of nodes: "nodeler"
        echo: yes
        timeout: 5

  become: yes
  become_user: "{{ secnode_user_name }}"

# Tracker service
- name: Create tracker service file
  copy:
    dest: "/lib/systemd/system/{{ secnode_tracker_svc_name }}.service"
    owner: root
    content: |
      [Unit]
      Description=ZenCash node daemon installed on {{ secnode_tracker_dir }}
      Requires={{ secnode_zend_svc_name }}.service
      After={{ secnode_zend_svc_name }}.service

      [Service]
      User={{ secnode_user_name }}
      Type=simple
      WorkingDirectory={{ secnode_tracker_dir }}
      ExecStart=/usr/local/bin/node {{ secnode_tracker_dir }}/app.js
      Restart=always
      RestartSec=10

      [Install]
      WantedBy=multi-user.target
  register: secnode_tracker_svc_file

- name: Systemd daemon-reload
  systemd:
    daemon_reload: true
  when: secnode_tracker_svc_file.changed

# Activate tracker
- name: Start and enable tracker service
  service:
    name: "{{ secnode_tracker_svc_name }}.service"
    enabled: yes
    state: started
