---
- name: Install Tracker Container
  docker_container:
    name: "{{ nodetracker_docker_ctr_name }}"
    image: "aschultz5/zen-nodetracker:{{ nodetracker_ver }}"
    state: present
    restart_policy: unless-stopped
    user: "{{ zend_user_id }}"
    log_driver: journald
    env:
      ZENCONF: /mnt/zen/zen.conf
    volumes:
      - "{{ nodetracker_dir }}/config:/home/node/app/config"
      - "{{ zend_dir }}:/mnt/zen:ro"
    networks:
      - name: "{{ zend_docker_net_name }}"

