# gc_storage dependencies
- name: Install python3-pip
  apt: name=python3-pip
- name: Install boto
  pip: name=boto

- name: Download wallet
  gc_storage:
    bucket: "{{ gcs_bucket }}"
    object: "/horizen/wallets/{{ inventory_hostname }}"
    dest: "{{ zend_dir }}/wallet.dat"
    mode: get
    gs_access_key: "{{ lookup('env', 'GCS_ACCESS_KEY_ID') }}"
    gs_secret_key: "{{ lookup('env', 'GCS_SECRET_ACCESS_KEY') }}"
- file:
    dest: "{{ zend_dir }}/wallet.dat"
    owner: "{{ zend_user_name }}"
    mode: 0600
  notify:
    - restart zend
